<?php

/**
 * @file
 * Functions to support theming in the Bartik theme.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;
use Drupal\views\Form\ViewsForm;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */

function bjc_theme_preprocess_node(&$variables) {
  $variables['homepage_slideshow'] =  views_embed_view('home_page_slideshow', 'block_1');
}
