<?php

/**
 * @file
 * Functions to support theming in the BJC theme.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body bjc theme if certain regions have content.
 */
function bjc_theme_preprocess_field(&$variables) {

}